openapi: 3.0.1
info:
  title: User and Organization Management API
  description: The Authentication and Organization Management API provides essential functionalities for user and organization management within an application. This API enables clients to perform user registration, user login, organization creation, and adding users to organizations. It is designed to facilitate secure and efficient management of users and their associations with organizations.
  version: "v1"
paths:
  /auth/login:
    post:
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginDto'
      responses:
        '200':
          description: Success
  /auth/register:
    post:
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistrationDto'
      responses:
        '200':
          description: Success
  /api/organisations:
    post:
      tags:
        - Organisations
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddOrganisationDto'
      responses:
        '200':
          description: Success
    get:
      tags:
        - Organisations
      responses:
        '200':
          description: Success
  /api/organisations/{orgId}:
    get:
      tags:
        - Organisations
      parameters:
        - name: orgId
          in: path
          required: true
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: Success
  /api/organisations/{orgId}/users:
    post:
      tags:
        - Organisations
      parameters:
        - name: orgId
          in: path
          required: true
          style: simple
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserIdDto'
      responses:
        '200':
          description: Success
  /api/Users/{userId}:
    get:
      tags:
        - Users
      parameters:
        - name: userId
          in: path
          required: true
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: Success
components:
  schemas:
    AddOrganisationDto:
      type: object
      properties:
        name:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
      additionalProperties: false
    LoginDto:
      type: object
      properties:
        email:
          type: string
          nullable: false
        password:
          type: string
          nullable: false
      additionalProperties: false
    UserIdDto:
      type: object
      properties:
        userId:
          type: string
          nullable: true
      additionalProperties: false
    UserRegistrationDto:
      type: object
      properties:
        firstName:
          type: string
          nullable: false
        lastName:
          type: string
          nullable: false
        email:
          type: string
          nullable: false
        password:
          type: string
          nullable: false
        phone:
          type: string
          nullable: true
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: apiKey
      description: "JWT Authorization header using the Bearer scheme. \r\n                      Enter 'Bearer' [space] and then your token in the text input below.\r\n                      Example: 'Bearer 12345abcdef'"
      name: Authorization
      in: header
security:
  - Bearer: []