name: Dev Deployment

on:
  push:
    branches:
      - dev

jobs:
  deploy_to_dev:
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest

    environment:
      name: "dev"
      url: ${{ vars.URL }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy To Dev Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd development/scripts
          ./dev-deploy.sh
