name: Staging Deployment

on:
  push:
    branches:
      - staging

jobs:
  deploy_to_staging:
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest

    environment:
      name: "staging"
      url: ${{ env.URL }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy To Staging Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd staging/scripts
          ./staging-deploy.sh
