name: Deploy

on:
  push: 
    branches: 
        - staging
jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: "staging"
      url: ${{env.URL}}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy To Stage Server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd hng_boilerplate_csharp_web/scripts
          git checkout staging
          git pull origin staging
          ./stage-deploy.sh